services:
  nginx:
    build: ./.nginx
    volumes:
      - .:/var/www/app
    ports:
      - 80:80
    env_file:
      - .env.prod
    networks:
      - app
  php:
    build: .
    env_file:
      - .env.prod
    networks:
      - app
networks:
  app:
    driver: bridge