services:
  nginx:
    build: ./.nginx
    restart: always
    environment:
      - APP_ENV=prod
    volumes:
      - .:/var/www/app
    ports:
      - 80:80
    networks:
      - app
  php:
    build: .
    restart: always
    environment:
      - APP_ENV=prod
    networks:
      - app
networks:
  app:
    driver: bridge