services:
  nginx:
    build: .nginx
    restart: always
    environment:
      - APP_ENV=prod
    volumes:
      - .:/var/www/app
    ports:
      - 80:80
    networks:
      - app
  php:
    build: .
    environment:
      - APP_ENV=prod
      - DATABASE_URL=mysql://root:root@database:3306/app?serverVersion=8.0.32&charset=utf8mb4
    depends_on:
      - database
    networks:
      - app
  database:
    container_name: database
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.mysql/data:/var/lib/mysql
    networks:
      - app
networks:
  app:
    driver: bridge