services:
  nginx:
    build: ./.nginx
    restart: always
    profiles:
      - prod
    environment:
      - APP_ENV=prod
    volumes:
      - .:/var/www/app
    ports:
      - 80:80
    depends_on:
      - php
    networks:
      - app
  php:
    build: .
    restart: always
    profiles:
      - prod
    environment:
      - APP_ENV=prod
    networks:
      - app
  database:
    container_name: database
    image: mysql
    restart: always
    profiles:
      - prod
      - dev
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.mysql/data:/var/lib/mysql
    networks:
      - app
    depends_on:
      - php
  phpmyadmin:
    image: phpmyadmin
    restart: always
    profiles:
      - dev
    ports:
      - 8080:80
    environment:
      PMA_HOST: database
    networks:
      - app
    depends_on:
      - database
networks:
  app:
    driver: bridge